---
title: "sars: an R package for fitting, comparing and evaluating species-area relationship [models]"
author: "Thomas J. Matthews* (1,2), Kostas Triantis, Robert J. Whittaker & Francois Guilhaumon"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

### Authors information

- (1) GEES (School of Geography, Earth and Environmental Sciences), The University of Birmingham, Birmingham, B15 2TT

- (2) 2CE3C – Centre for Ecology, Evolution and Environmental Changes/Azorean Biodiversity Group and Univ. dos Açores – Depto de Ciências e Engenharia do Ambiente, PT-9700-042, Angra do Heroísmo, Açores, Portugal.

*Correspondence: Thomas J. Matthews, School of Geography, Earth and Environmental Sciences, University of Birmingham, Birmingham, B15 2TT, UK

Email: t.j.matthews@bham.ac.uk


### Running header: sars R package

### Word count: abstract: words; main text =  words;  Tables;  Figures; references; appendices

### Keywords  
Diversity-area relationship, island biogeography, multi-model inference, power model, species accumulation curve, species-area relationship, random placement model

# Summary

# Introduction

The species–area relationship (SAR) describes the near universally observed pattern whereby the number of species increases with the area sampled, and it has been described as one of ecology’s few laws (Rosenzweig, 1995). The SAR is a fundamental component of myriad ecological and biogeographical theories, such as the equilibrium theory of island biogeography (MacArthur & Wilson, 1967). In addition, SAR models have been widely used in applied ecology and conservation biogeography; for example, to predict the number of extinctions due to habitat loss (He & Hubbell, 2011). Numerous types of SAR have been described, and one primary dichotomy employed is the split of SARs into island SARs (ISARs), whereby each data point is an individual island or isolated sample, and species accumulation curves (SACs), that represent cumulative counts of increased species number with sampling area (Gray et al., 2004). Whilst the remainder of the paper and the described R package are focused on ISARs, the models and the model fitting procedure can equally be applied to SACs (see Matthews et al., 2016), although it should be noted that in SACs the data points are not independent of one another. 

Over twenty SAR models have been described in the literature (Tjørve, 2003, Triantis et al., 2012). However, despite this wide range of models, the majority of SAR studies are still based exclusively on the power model (Arrhenius, 1921). Often, the log-log interpretation of the power model is used as it can be fitted using standard linear regression, and its parameters are more easily interpretable (Rosenzweig, 1995). However, whilst the power model has been found to provide a reasonable fit to a wide range of datasets (Triantis et al., 2012), it is not universally the best model, and a number of studies have reported other models, and perhaps more importantly, other model shapes, to provide better fits to empirical data than the convex power model (e.g. Triantis et al., 2012; Benchimol & Peres, 2013; Matthews et al., 2015). For example, the scale dependency of the SAR has long been recognised, such that at intermediate scales the form is predicted to be approximated by a power model, whilst at larger spatial scales the form of the SAR is theorised to be sigmoidal (He & Legendre, 1996). 

Due to the increased recognition of model uncertainty in SAR research, a number of recent studies have employed a multi-model inference approach (Burnham & Anderson, 2002) in the analysis of SARs, whereby either (1) multiple SAR models are compared using various criteria (e.g. AIC) and a best model is chosen (e.g. Benchimol & Peres, 2013), or (2) multiple SAR models are fitted and a multi-model averaged curve is calculated using, for example, AIC weights (e.g. Guilhaumon et al., 2008). However, no software package exists that enables users to fit, and create multi-model averaged curves using, more than eight SAR models. 

To address these concerns, we have developed the R package ‘sars’ that provides a wide variety of SAR related functionality. The package provides functions to fit twenty SAR model using non-linear and linear regression, calculate multi-model averaged curves using various information criteria, and generate confidence intervals using bootstrapping. In regards to other available software, the BAT R package (Cardoso et al., 2014) provides functions to fit three SAR models (linear, power and exponential); however, this package is focused on general biodiversity assessment and thus does not provide any additional SAR functionality. The main SAR software currently available is the mmSAR R package (Guilhaumon et al., 2010), which allows user to fit eight SAR models using an information theoretic framework. Thus, it does not include a large number of models that have been found to provide the best fits to several empirical datasets (Matthews et al., 2015). In addition to allowing users to fit up to twenty competing SAR models, the ‘sars’ package has more additional user-friendly functions, e.g. for plotting (can now plot multimodel SAR curve with the other individual SAR model curves and confidence intervals) than mmSAR, and provides additional SAR functionality, such as functions to fit, plot and evaluate Coleman’s (1982) random placement model using a species-site abundance matrix (/code{function}), and to fit the general dynamic model (GDM) of island biogeography (Borregaard et al., 2017) using any of 20 SAR models (/code{function}). In addition, the mmSAR package (which will be deprecated) no longer complies with recent programming good practices, is not on CRAN (the main repository of R package), is not user friendly (e.g. it requires the user to load individual models prior to fitting), and since it was published in 2010 there have been many advances in R packages and functionality (see Wickham, 2015) that are lacking in mmSAR. As such, there is the need for a new package to be designed from scratch. 

‘sars’ has been programmed using standard S3 methods and is available on CRAN (version 1.0.0; R Core Team, 2017) and GitHub (txm676/sars), meaning researchers can easily add in their own models and functions (e.g. recently developed countryside biogeography SAR models; Pereira et al., 2014) and integrate these into the multi-model inference framework. Thus, the package represents a resource for future SAR work that can be built on and expanded by workers in the field.



# Package description


Following Guilhaumon et al. (2010), the sars package uses non-linear regression

## Initial parameters (custstart)


## Theoretical and observed shape (latter is a novelty to this paper)


## Class mmsar2 and nls

## Additional functions

In addition to the main functions used to fit and compare the twenty SAR models, the sars package provides additional functions for specific SAR based analyses. 

## Linear power (log version) and parameter comparisons

## Coleman


# Examples



# Conclusions

Done in general way so people can add new models etc
state that it is mmSAR but is for fitting multi-model diversity area relationships, a la Mazel.

# Authors’ contributions

# Acknowledgements 

# Data accessibility 

# References 
